# Meta Data for SEO

## Homepage
title = "Famland.World"
titleSeparator = "-"
titleAddition = "Famland Metaverse"
description = "Famland Metaverse"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["famland.png"]
ogLocale = "en_US"
domainTLD = "famland.world"
titleHome = "Doks Theme"

## Twitter Cards
twitterSite = "@getdoks"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "famland.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/famlandworld"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/famland/website/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [1280, 1200, 1100, 1000, 900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://famland.world/\">Famland Metaverse</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = false 
alertDismissable = false
alertText = "Famland New Decentralized Website Lunched！<a class=\"alert-link stretched-link\" href=\"/blog/famland-decentralized-website-officially-released/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Famland元宇宙部署EOS公链上线计划公告📢 <a class=\"alert-link stretched-link\" href=\"/blog/2022-04-28/\">>>>></a>"



# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/famland/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = true

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
